search_key: sosiremi
self_url: https://nikolat.github.io/sosiremi/
site_title: 偽SoSiReMi
site_description: GitHubで公開されているNARファイルを一覧表示する
redirect:
  Taromati2/Taromati2:
    nar: Taromati2/package-factory
    readme: https://raw.githubusercontent.com/Taromati2/Taromati2/master/.ukagaka/infos/sosiremi.txt
